- code: sh600460
  condition: <
  indicator: RSI
  name: 士兰微-RSI超卖预警
  threshold: 30
- code: sh600460
  condition: '>'
  indicator: Close
  name: 士兰微-突破MA20
  threshold: MA20
- code: sh600460
  condition: '>'
  indicator: DIF
  name: 士兰微-MACD金叉
  threshold: DEA
- code: HK.00700
  condition: '>'
  indicator: K
  name: 腾讯控股-KDJ超买预警
  threshold: 80
- code: HK.00700
  condition: '>'
  indicator: Volume_Ratio
  name: 腾讯控股-成交量异动
  threshold: 1.5
- code: HK.00700
  condition: <
  indicator: Close
  name: 腾讯控股-跌破MA60预警
  threshold: MA60
- code: sh688630
  condition: '>'
  indicator: Close
  name: 芯碁微装-不跌破前期低点
  threshold: 178
- code: sh688630
  condition: '>='
  indicator: Close
  name: 芯碁微装-回落企稳区间下限
  threshold: 179
- code: sh688630
  condition: '<='
  indicator: Close
  name: 芯碁微装-回落企稳区间上限
  threshold: 180
- code: sh688630
  condition: '>'
  indicator: MACD
  name: 芯碁微装-MACD转强
  threshold: 0
